BUNDLES = [
    "//apps/ids/app:onos-apps-ids-app",
]

onos_app(
    category = "Monitoring",
    description = "IDS application that retrieves flow statistics and sends them to an external classifier.",
    included_bundles = BUNDLES,
    title = "SDN IDS Monitor",
    url = "http://onosproject.org",
)