BUNDLES = [
    "//apps/sbm/web:onos-apps-sbm-web",
    "//apps/sbm/app:onos-apps-sbm-app",
]

onos_app(
    category = "Monitoring",
    description = "Listens to OpenFlow PacketIn messages and learns source MAC addresses, " +
                  "storing them in a local MAC table.",
    included_bundles = BUNDLES,
    title = "Southbound MAC Monitor",
    url = "http://onosproject.org",
)

